/**
 * CameraSettingsConfig - Configuration definitions for camera settings UI
 *
 * Separated from UI to keep file sizes manageable
 */
export const CAMERA_SETTINGS_CONFIG = {
    basicMovement: [
        {
            key: 'sensitivity',
            label: 'Camera Sensitivity',
            min: 0.001,
            max: 0.05,
            step: 0.001,
            format: (v) => v.toFixed(3),
        },
        {
            key: 'zoomSpeed',
            label: 'Zoom Speed',
            min: 0.1,
            max: 2.0,
            step: 0.1,
            format: (v) => v.toFixed(1),
        },
        {
            key: 'autoAlignSpeed',
            label: 'Auto-Align Speed',
            min: 0.5,
            max: 8.0,
            step: 0.5,
            format: (v) => v.toFixed(1),
        },
        {
            key: 'springStiffness',
            label: 'Spring Stiffness (Smoothness)',
            min: 0.01,
            max: 0.5,
            step: 0.01,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'springDamping',
            label: 'Spring Damping (Responsiveness)',
            min: 0.1,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
    ],

    advancedMovement: [
        {
            key: 'followSmoothness',
            label: 'Follow Smoothness',
            min: 0.01,
            max: 0.5,
            step: 0.01,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'distanceTransitionSpeed',
            label: 'Distance Transition Speed',
            min: 0.05,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'angleTransitionSpeed',
            label: 'Angle Transition Speed',
            min: 0.05,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'autoAlignDelay',
            label: 'Auto-Align Delay (seconds)',
            min: 0.5,
            max: 5.0,
            step: 0.1,
            format: (v) => v.toFixed(1) + 's',
        },
        {
            key: 'microJitterAmount',
            label: 'Micro Jitter Amount',
            min: 0.0,
            max: 0.01,
            step: 0.0001,
            format: (v) => v.toFixed(4),
        },
    ],

    cameraEffects: [
        {
            key: 'shakeIntensityMultiplier',
            label: 'Shake Intensity Multiplier',
            min: 0.0,
            max: 2.0,
            step: 0.1,
            format: (v) => v.toFixed(1) + 'x',
        },
        {
            key: 'shakeDecayRate',
            label: 'Shake Decay Rate',
            min: 1.0,
            max: 20.0,
            step: 0.5,
            format: (v) => v.toFixed(1),
        },
        {
            key: 'wildMomentEffectsIntensity',
            label: 'Wild Moment Effects Intensity',
            min: 0.0,
            max: 2.0,
            step: 0.1,
            format: (v) => v.toFixed(1) + 'x',
        },
        {
            key: 'cameraRollTiltAmount',
            label: 'Camera Roll/Tilt Amount',
            min: 0.0,
            max: 0.2,
            step: 0.01,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'headBobAmount',
            label: 'Head Bob Amount',
            min: 0.0,
            max: 0.1,
            step: 0.01,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'headBobSpeed',
            label: 'Head Bob Speed',
            min: 0.0,
            max: 5.0,
            step: 0.1,
            format: (v) => v.toFixed(1),
        },
    ],

    modeSpecific: [
        {
            key: 'cinematicOrbitSpeed',
            label: 'Cinematic Orbit Speed',
            min: 0.05,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'cinematicOrbitRadius',
            label: 'Cinematic Orbit Radius',
            min: 5,
            max: 20,
            step: 0.5,
            format: (v) => v.toFixed(1),
        },
        {
            key: 'lockOnTransitionSpeed',
            label: 'Lock-On Transition Speed',
            min: 0.05,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'freecamMovementSpeed',
            label: 'Freecam Movement Speed',
            min: 0.1,
            max: 5.0,
            step: 0.1,
            format: (v) => v.toFixed(1),
        },
        {
            key: 'freecamRotationSpeed',
            label: 'Freecam Rotation Speed',
            min: 0.1,
            max: 2.0,
            step: 0.1,
            format: (v) => v.toFixed(1),
        },
    ],

    postProcessing: [
        {
            key: 'chromaticAberrationIntensity',
            label: 'Chromatic Aberration Intensity',
            min: 0.0,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'glitchEffectIntensity',
            label: 'Glitch Effect Intensity',
            min: 0.0,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'screenShakeFromEffects',
            label: 'Screen Shake from Effects',
            min: 0.0,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
        {
            key: 'visualDistortionIntensity',
            label: 'Visual Distortion Intensity',
            min: 0.0,
            max: 1.0,
            step: 0.05,
            format: (v) => v.toFixed(2),
        },
    ],

    toggles: {
        advancedMovement: [{ key: 'microJitterEnabled', label: 'Enable Micro Jitter' }],
        cameraEffects: [{ key: 'bassReactiveShakeEnabled', label: 'Enable Bass-Reactive Shake' }],
        postProcessing: [{ key: 'motionBlurEnabled', label: 'Enable Motion Blur' }],
    },
};
